//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = module.exports = {};
if (typeof nexx === 'undefined') {
  nexx = {};
}
if (typeof nexx.shared === 'undefined') {
  nexx.shared = {};
}
nexx.shared.UpdateOptions = module.exports.UpdateOptions = function(args) {
  this.allowNull = false;
  this.allowZero = true;
  this.allowEmpty = false;
  if (args) {
    if (args.allowNull !== undefined && args.allowNull !== null) {
      this.allowNull = args.allowNull;
    }
    if (args.allowZero !== undefined && args.allowZero !== null) {
      this.allowZero = args.allowZero;
    }
    if (args.allowEmpty !== undefined && args.allowEmpty !== null) {
      this.allowEmpty = args.allowEmpty;
    }
  }
};
nexx.shared.UpdateOptions.prototype = {};
nexx.shared.UpdateOptions.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.BOOL) {
        this.allowNull = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.BOOL) {
        this.allowZero = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.BOOL) {
        this.allowEmpty = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

nexx.shared.UpdateOptions.prototype.write = function(output) {
  output.writeStructBegin('UpdateOptions');
  if (this.allowNull !== null && this.allowNull !== undefined) {
    output.writeFieldBegin('allowNull', Thrift.Type.BOOL, 1);
    output.writeBool(this.allowNull);
    output.writeFieldEnd();
  }
  if (this.allowZero !== null && this.allowZero !== undefined) {
    output.writeFieldBegin('allowZero', Thrift.Type.BOOL, 2);
    output.writeBool(this.allowZero);
    output.writeFieldEnd();
  }
  if (this.allowEmpty !== null && this.allowEmpty !== undefined) {
    output.writeFieldBegin('allowEmpty', Thrift.Type.BOOL, 3);
    output.writeBool(this.allowEmpty);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

nexx.shared.SelectOptions = module.exports.SelectOptions = function(args) {
  this.includes = null;
  this.order = null;
  this.limit = null;
  this.offset = null;
  if (args) {
    if (args.includes !== undefined && args.includes !== null) {
      this.includes = Thrift.copyList(args.includes, [null]);
    }
    if (args.order !== undefined && args.order !== null) {
      this.order = args.order;
    }
    if (args.limit !== undefined && args.limit !== null) {
      this.limit = args.limit;
    }
    if (args.offset !== undefined && args.offset !== null) {
      this.offset = args.offset;
    }
  }
};
nexx.shared.SelectOptions.prototype = {};
nexx.shared.SelectOptions.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.LIST) {
        var _size0 = 0;
        var _rtmp34;
        this.includes = [];
        var _etype3 = 0;
        _rtmp34 = input.readListBegin();
        _etype3 = _rtmp34.etype;
        _size0 = _rtmp34.size;
        for (var _i5 = 0; _i5 < _size0; ++_i5)
        {
          var elem6 = null;
          elem6 = input.readString();
          this.includes.push(elem6);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.order = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.limit = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.I32) {
        this.offset = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

nexx.shared.SelectOptions.prototype.write = function(output) {
  output.writeStructBegin('SelectOptions');
  if (this.includes !== null && this.includes !== undefined) {
    output.writeFieldBegin('includes', Thrift.Type.LIST, 1);
    output.writeListBegin(Thrift.Type.STRING, this.includes.length);
    for (var iter7 in this.includes)
    {
      if (this.includes.hasOwnProperty(iter7))
      {
        iter7 = this.includes[iter7];
        output.writeString(iter7);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  if (this.order !== null && this.order !== undefined) {
    output.writeFieldBegin('order', Thrift.Type.STRING, 2);
    output.writeString(this.order);
    output.writeFieldEnd();
  }
  if (this.limit !== null && this.limit !== undefined) {
    output.writeFieldBegin('limit', Thrift.Type.I32, 3);
    output.writeI32(this.limit);
    output.writeFieldEnd();
  }
  if (this.offset !== null && this.offset !== undefined) {
    output.writeFieldBegin('offset', Thrift.Type.I32, 4);
    output.writeI32(this.offset);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

