//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var product_ttypes = require('./product_types')
var product_color_ttypes = require('./product_color_types')


var ttypes = module.exports = {};
if (typeof vv === 'undefined') {
  vv = {};
}
if (typeof vv.models === 'undefined') {
  vv.models = {};
}
vv.models.QuoteItem = module.exports.QuoteItem = function(args) {
  this.id = null;
  this.quoteId = null;
  this.productId = null;
  this.selectedProductColorId = null;
  this.quantity = null;
  this.basePrice = null;
  this.product = null;
  this.productColor = null;
  if (args) {
    if (args.id !== undefined && args.id !== null) {
      this.id = args.id;
    }
    if (args.quoteId !== undefined && args.quoteId !== null) {
      this.quoteId = args.quoteId;
    }
    if (args.productId !== undefined && args.productId !== null) {
      this.productId = args.productId;
    }
    if (args.selectedProductColorId !== undefined && args.selectedProductColorId !== null) {
      this.selectedProductColorId = args.selectedProductColorId;
    }
    if (args.quantity !== undefined && args.quantity !== null) {
      this.quantity = args.quantity;
    }
    if (args.basePrice !== undefined && args.basePrice !== null) {
      this.basePrice = args.basePrice;
    }
    if (args.product !== undefined && args.product !== null) {
      this.product = new product_ttypes.Product(args.product);
    }
    if (args.productColor !== undefined && args.productColor !== null) {
      this.productColor = new product_color_ttypes.ProductColor(args.productColor);
    }
  }
};
vv.models.QuoteItem.prototype = {};
vv.models.QuoteItem.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.id = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.quoteId = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.productId = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.I32) {
        this.selectedProductColorId = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.DOUBLE) {
        this.quantity = input.readDouble();
      } else {
        input.skip(ftype);
      }
      break;
      case 6:
      if (ftype == Thrift.Type.DOUBLE) {
        this.basePrice = input.readDouble();
      } else {
        input.skip(ftype);
      }
      break;
      case 7:
      if (ftype == Thrift.Type.STRUCT) {
        this.product = new product_ttypes.Product();
        this.product.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 8:
      if (ftype == Thrift.Type.STRUCT) {
        this.productColor = new product_color_ttypes.ProductColor();
        this.productColor.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

vv.models.QuoteItem.prototype.write = function(output) {
  output.writeStructBegin('QuoteItem');
  if (this.id !== null && this.id !== undefined) {
    output.writeFieldBegin('id', Thrift.Type.I32, 1);
    output.writeI32(this.id);
    output.writeFieldEnd();
  }
  if (this.quoteId !== null && this.quoteId !== undefined) {
    output.writeFieldBegin('quoteId', Thrift.Type.I32, 2);
    output.writeI32(this.quoteId);
    output.writeFieldEnd();
  }
  if (this.productId !== null && this.productId !== undefined) {
    output.writeFieldBegin('productId', Thrift.Type.I32, 3);
    output.writeI32(this.productId);
    output.writeFieldEnd();
  }
  if (this.selectedProductColorId !== null && this.selectedProductColorId !== undefined) {
    output.writeFieldBegin('selectedProductColorId', Thrift.Type.I32, 4);
    output.writeI32(this.selectedProductColorId);
    output.writeFieldEnd();
  }
  if (this.quantity !== null && this.quantity !== undefined) {
    output.writeFieldBegin('quantity', Thrift.Type.DOUBLE, 5);
    output.writeDouble(this.quantity);
    output.writeFieldEnd();
  }
  if (this.basePrice !== null && this.basePrice !== undefined) {
    output.writeFieldBegin('basePrice', Thrift.Type.DOUBLE, 6);
    output.writeDouble(this.basePrice);
    output.writeFieldEnd();
  }
  if (this.product !== null && this.product !== undefined) {
    output.writeFieldBegin('product', Thrift.Type.STRUCT, 7);
    this.product.write(output);
    output.writeFieldEnd();
  }
  if (this.productColor !== null && this.productColor !== undefined) {
    output.writeFieldBegin('productColor', Thrift.Type.STRUCT, 8);
    this.productColor.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

vv.models.QuoteItemInsert = module.exports.QuoteItemInsert = function(args) {
  this.quoteId = null;
  this.productId = null;
  this.selectedProductColorId = null;
  this.quantity = null;
  this.basePrice = null;
  if (args) {
    if (args.quoteId !== undefined && args.quoteId !== null) {
      this.quoteId = args.quoteId;
    }
    if (args.productId !== undefined && args.productId !== null) {
      this.productId = args.productId;
    }
    if (args.selectedProductColorId !== undefined && args.selectedProductColorId !== null) {
      this.selectedProductColorId = args.selectedProductColorId;
    }
    if (args.quantity !== undefined && args.quantity !== null) {
      this.quantity = args.quantity;
    }
    if (args.basePrice !== undefined && args.basePrice !== null) {
      this.basePrice = args.basePrice;
    }
  }
};
vv.models.QuoteItemInsert.prototype = {};
vv.models.QuoteItemInsert.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.quoteId = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.productId = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.selectedProductColorId = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.DOUBLE) {
        this.quantity = input.readDouble();
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.DOUBLE) {
        this.basePrice = input.readDouble();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

vv.models.QuoteItemInsert.prototype.write = function(output) {
  output.writeStructBegin('QuoteItemInsert');
  if (this.quoteId !== null && this.quoteId !== undefined) {
    output.writeFieldBegin('quoteId', Thrift.Type.I32, 1);
    output.writeI32(this.quoteId);
    output.writeFieldEnd();
  }
  if (this.productId !== null && this.productId !== undefined) {
    output.writeFieldBegin('productId', Thrift.Type.I32, 2);
    output.writeI32(this.productId);
    output.writeFieldEnd();
  }
  if (this.selectedProductColorId !== null && this.selectedProductColorId !== undefined) {
    output.writeFieldBegin('selectedProductColorId', Thrift.Type.I32, 3);
    output.writeI32(this.selectedProductColorId);
    output.writeFieldEnd();
  }
  if (this.quantity !== null && this.quantity !== undefined) {
    output.writeFieldBegin('quantity', Thrift.Type.DOUBLE, 4);
    output.writeDouble(this.quantity);
    output.writeFieldEnd();
  }
  if (this.basePrice !== null && this.basePrice !== undefined) {
    output.writeFieldBegin('basePrice', Thrift.Type.DOUBLE, 5);
    output.writeDouble(this.basePrice);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

vv.models.QuoteItemForm = module.exports.QuoteItemForm = function(args) {
  this.id = null;
  this.quantity = null;
  this.basePrice = null;
  this.status = null;
  if (args) {
    if (args.id !== undefined && args.id !== null) {
      this.id = args.id;
    }
    if (args.quantity !== undefined && args.quantity !== null) {
      this.quantity = args.quantity;
    }
    if (args.basePrice !== undefined && args.basePrice !== null) {
      this.basePrice = args.basePrice;
    }
    if (args.status !== undefined && args.status !== null) {
      this.status = args.status;
    }
  }
};
vv.models.QuoteItemForm.prototype = {};
vv.models.QuoteItemForm.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.id = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.DOUBLE) {
        this.quantity = input.readDouble();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.DOUBLE) {
        this.basePrice = input.readDouble();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.I32) {
        this.status = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

vv.models.QuoteItemForm.prototype.write = function(output) {
  output.writeStructBegin('QuoteItemForm');
  if (this.id !== null && this.id !== undefined) {
    output.writeFieldBegin('id', Thrift.Type.I32, 1);
    output.writeI32(this.id);
    output.writeFieldEnd();
  }
  if (this.quantity !== null && this.quantity !== undefined) {
    output.writeFieldBegin('quantity', Thrift.Type.DOUBLE, 2);
    output.writeDouble(this.quantity);
    output.writeFieldEnd();
  }
  if (this.basePrice !== null && this.basePrice !== undefined) {
    output.writeFieldBegin('basePrice', Thrift.Type.DOUBLE, 3);
    output.writeDouble(this.basePrice);
    output.writeFieldEnd();
  }
  if (this.status !== null && this.status !== undefined) {
    output.writeFieldBegin('status', Thrift.Type.I32, 4);
    output.writeI32(this.status);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

