//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var geo_ttypes = require('./geo_types')
var exception_ttypes = require('./exception_types')
var client_id_ttypes = require('./client_id_types')
var access_token_ttypes = require('./access_token_types')
var customer_ttypes = require('./customer_types')
var customer_address_ttypes = require('./customer_address_types')
var options_ttypes = require('./options_types')
var country_ttypes = require('./country_types')
var product_ttypes = require('./product_types')
var product_color_ttypes = require('./product_color_types')
var product_color_preview_image_ttypes = require('./product_color_preview_image_types')
var category_ttypes = require('./category_types')
var category_group_ttypes = require('./category_group_types')
var pagination_ttypes = require('./pagination_types')
var province_ttypes = require('./province_types')
var district_ttypes = require('./district_types')
var ward_ttypes = require('./ward_types')
var quote_ttypes = require('./quote_types')
var quote_item_ttypes = require('./quote_item_types')
var quote_payment_ttypes = require('./quote_payment_types')
var order_ttypes = require('./order_types')
var order_item_ttypes = require('./order_item_types')
var order_payment_ttypes = require('./order_payment_types')
var order_status_history_ttypes = require('./order_status_history_types')


var ttypes = module.exports = {};
if (typeof vv === 'undefined') {
  vv = {};
}
if (typeof vv.service === 'undefined') {
  vv.service = {};
}
